/**
 * agents:sync — renders the canonical, tool-neutral agent definitions into each runtime's format.
 *
 *   npm run agents:sync     write the adapters
 *   npm run agents:check    exit 1 if any adapter is missing, edited by hand, or orphaned
 *
 *   agents/<name>.md            → .claude/agents/<name>.md           (Claude Code)
 *                                 .github/agents/<name>.agent.md     (GitHub Copilot custom agent)
 *                                 .opencode/agents/<name>.md         (opencode, mode: subagent)
 *   agents/playbooks/<name>.md  → .claude/skills/<name>/SKILL.md     (Claude Code skill)
 *                                 .github/prompts/<name>.prompt.md   (Copilot prompt file)
 *                                 .opencode/commands/<name>.md       (opencode command)
 *
 * Canonical frontmatter uses generic capabilities (see CAPABILITIES) instead of tool names.
 */
import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';

export const CAPABILITIES = ['read', 'search', 'write', 'edit', 'shell', 'web', 'catalog'] as const;
export type Capability = (typeof CAPABILITIES)[number];

export interface Canonical {
  kind: 'agent' | 'playbook';
  name: string;
  description: string;
  tools: Capability[];
  file: string;
  body: string;
}

export const MARKER = 'GENERATED by `npm run agents:sync`';
const banner = (src: string) => `<!-- ${MARKER} from ${src} — edit that file, not this one. -->`;

function parse(file: string, kind: Canonical['kind'], root: string): Canonical {
  const raw = fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) throw new Error(`${file}: missing frontmatter`);
  const fm = (YAML.parse(m[1]) ?? {}) as Record<string, unknown>;
  const name = String(fm.name ?? path.basename(file, '.md'));
  if (name !== path.basename(file, '.md')) throw new Error(`${file}: name "${name}" must match the file name`);
  if (!fm.description) throw new Error(`${file}: description is required`);
  const tools = ([] as unknown[]).concat(fm.tools ?? []).map(String) as Capability[];
  const unknown = tools.filter((t) => !CAPABILITIES.includes(t));
  if (unknown.length) throw new Error(`${file}: unknown tools ${unknown.join(', ')} (use ${CAPABILITIES.join(', ')})`);
  return {
    kind,
    name,
    description: String(fm.description).trim(),
    tools,
    file: path.relative(root, file).split(path.sep).join('/'),
    body: raw.slice(m[0].length).trim(),
  };
}

export function loadCanonical(root = '.'): Canonical[] {
  const dir = path.join(root, 'agents');
  const md = (d: string) => (fs.existsSync(d) ? fs.readdirSync(d).filter((f) => f.endsWith('.md') && f !== 'README.md').sort() : []);
  return [
    ...md(dir).map((f) => parse(path.join(dir, f), 'agent', root)),
    ...md(path.join(dir, 'playbooks')).map((f) => parse(path.join(dir, 'playbooks', f), 'playbook', root)),
  ];
}

const frontmatter = (o: Record<string, unknown>) => `---\n${YAML.stringify(o, { lineWidth: 0 }).trim()}\n---\n`;

// A catalog (MCP) server is named by whoever configures it, so no adapter can list its tools.
// Agents that need it get no tool allow-list, which every runtime treats as "all tools".
const claudeTools: Record<Capability, string[]> = {
  read: ['Read'], search: ['Glob', 'Grep'], write: ['Write'], edit: ['Edit'], shell: ['Bash'], web: ['WebFetch', 'WebSearch'], catalog: [],
};
const copilotTools: Record<Capability, string[]> = {
  read: ['read'], search: ['search'], write: ['edit'], edit: ['edit'], shell: ['execute'], web: ['web'], catalog: [],
};
const mapTools = (c: Canonical, table: Record<Capability, string[]>) => [...new Set(c.tools.flatMap((t) => table[t]))];

function agentAdapters(c: Canonical): [string, string][] {
  const body = `${banner(c.file)}\n\n${c.body}\n`;
  const all = c.tools.includes('catalog');
  const claude = { name: c.name, description: c.description, ...(all ? {} : { tools: mapTools(c, claudeTools).join(', ') }) };
  const copilot = { name: c.name, description: c.description, ...(all ? {} : { tools: mapTools(c, copilotTools) }) };
  const can = (...t: Capability[]) => (t.some((x) => c.tools.includes(x)) ? 'allow' : 'deny');
  const opencode = { description: c.description, mode: 'subagent', permission: { edit: can('write', 'edit'), bash: can('shell'), webfetch: can('web') } };
  return [
    [`.claude/agents/${c.name}.md`, frontmatter(claude) + body],
    [`.github/agents/${c.name}.agent.md`, frontmatter(copilot) + body],
    [`.opencode/agents/${c.name}.md`, frontmatter(opencode) + body],
  ];
}

function playbookAdapters(c: Canonical): [string, string][] {
  const body = `${banner(c.file)}\n\n${c.body}\n`;
  return [
    [`.claude/skills/${c.name}/SKILL.md`, frontmatter({ name: c.name, description: c.description }) + body],
    [`.github/prompts/${c.name}.prompt.md`, frontmatter({ name: c.name, description: c.description, agent: 'agent' }) + body],
    [`.opencode/commands/${c.name}.md`, frontmatter({ description: c.description }) + body],
  ];
}

/** Every adapter file that should exist, keyed by repo-relative path. */
export function renderAdapters(canonical: Canonical[]): Map<string, string> {
  return new Map(canonical.flatMap((c) => (c.kind === 'agent' ? agentAdapters(c) : playbookAdapters(c))));
}

const ADAPTER_DIRS = ['.claude/agents', '.claude/skills', '.github/agents', '.github/prompts', '.opencode/agents', '.opencode/commands'];

/** Generated files on disk (they carry MARKER); hand-written runtime files are left alone. */
export function generatedOnDisk(root = '.'): string[] {
  const walk = (d: string): string[] =>
    !fs.existsSync(d) ? [] : fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]));
  return ADAPTER_DIRS.flatMap((d) => walk(path.join(root, d)))
    .filter((f) => f.endsWith('.md') && fs.readFileSync(f, 'utf8').includes(MARKER))
    .map((f) => path.relative(root, f).split(path.sep).join('/'));
}

export interface Drift {
  missing: string[];
  changed: string[];
  orphaned: string[];
}

export function checkAdapters(root = '.'): Drift {
  const want = renderAdapters(loadCanonical(root));
  const drift: Drift = { missing: [], changed: [], orphaned: [] };
  for (const [rel, content] of want) {
    const file = path.join(root, rel);
    if (!fs.existsSync(file)) drift.missing.push(rel);
    else if (fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== content) drift.changed.push(rel);
  }
  drift.orphaned = generatedOnDisk(root).filter((rel) => !want.has(rel));
  return drift;
}

export function writeAdapters(root = '.'): string[] {
  const want = renderAdapters(loadCanonical(root));
  for (const rel of generatedOnDisk(root)) if (!want.has(rel)) fs.rmSync(path.join(root, rel));
  for (const [rel, content] of want) {
    fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
    fs.writeFileSync(path.join(root, rel), content);
  }
  return [...want.keys()];
}

if (require.main === module) {
  if (process.argv.includes('--check')) {
    const d = checkAdapters();
    const problems = [...d.missing.map((f) => `missing  ${f}`), ...d.changed.map((f) => `changed  ${f}`), ...d.orphaned.map((f) => `orphaned ${f}`)];
    if (problems.length) {
      console.error(`Agent adapters are out of sync with agents/ — run \`npm run agents:sync\`:\n${problems.join('\n')}`);
      process.exit(1);
    }
    console.log('Agent adapters are in sync with agents/.');
  } else {
    const files = writeAdapters();
    console.log(`Wrote ${files.length} adapter files from agents/:\n${files.map((f) => `  ${f}`).join('\n')}`);
  }
}
